apiVersion: v1
kind: ConfigMap
metadata:
  name: email-provider-env
data:
  EMAIL_FROM_ADDRESS: email_from_address
  EMAIL_FROM_NAME: email_from_name
  EMAIL_NAME_TO: email_to_name
  EMAIL_TO_ADDRESS: email_to_address
  EMAIL_SUBJECT: email_subject