apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calidum-rotae-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
  - secretName: calidum-rotae-service-tls
    hosts:
    - calidum-rotae.omni.cedille.club
  rules:
  - host: calidum-rotae.omni.cedille.club
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: calidum-rotae-service
            port:
              number: 3000