apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: testcedille-

resources:
  - ../../../../bases/grav

patches:
  - path: vault-patch.yaml
  - target:
      kind: Ingress
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: test2.cedille.club
      - op: replace
        path: /spec/tls/0/hosts/0
        value: test2.cedille.club
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/testcedille-grav/default/grav
